apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYWludWwzNSIsInBhc3N3b3JkIjoiMUBEbEg0NDUhblEiLCJlbWFpbCI6Im1haW51bHMxOEBnbWFpbC5jb20iLCJhdXRoIjoiYldGcGJuVnNNelU2TVVCRWJFZzBORFVoYmxFPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
